name: dist

on:
  push:
    tags:
      - 'release/*'

permissions:
  contents: write

jobs:
  dist:
    name: build dist
    runs-on: macos-15
    timeout-minutes: 10
    defaults:
      run:
        shell: bash -euo pipefail {0}

    steps:
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2

      - name: test
        run: |
          make test-ci

      - name: build dist
        run: |
          make dist

      - name: Create GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.ref_name }}
        run: |
          V="${VERSION#release/}"
          gh release create "$VERSION" "tty.app.zip#tty-${V}-aarch64-apple-darwin.zip" --title "$V"
